### PR TITLE
Implement Destination Unreachable for ICMPv6

### PR DESCRIPTION
**Pull request by plumenator**
Co-authored-by: @Adenylatcyclase

## Description

Fixes # (issue) - if applicable

## Type of change

- [ ] Bug fix
- [x] New feature
- [ ] New protocol
- [ ] Breaking change
- [ ] Documentation update

## Checklist

- [x] Associated tests
- [x] Associated documentation

We based it on Time Exceeded, pretty much copy pasted and renamed identifiers. 😁 
This should tick one box off #105

### CODE REVIEW

**Comment by zeeshanlakhani** [comment]
@plumenator very cool to see this. Before @drunkirishcoder and I give it a good review, can you rebase and bring in the latest changes from the main branch?

**Comment by plumenator** [comment]
Done!

**Comment by zeeshanlakhani** [comment]
Thanks @plumenator @Adenylatcyclase. We'll take a gander this week.

**Review by drunkirishcoder — APPROVED** [review]
thank you for the contribution! good work.

**Review by zeeshanlakhani — APPROVED** [review]
Great work and for keeping up w/ our documentation approach too!

**Pull request merged**
